print("jangan lari")
print("jangan meroko")
print("selamat datang vicky")
print("dilarang  membuang smapah sembarangan")
print("jangan bertengkar")
print("dilarang parkair disini")
print("apa kabarmu")
print("halo semuanya")
print("selamt ulang tahun kebot")
print("trimakasih")